webserver:
  build: .
  volumes:
    - .:/usr/src/app
  ports:
    - 3000:80
  command: http-server ./ui/public -c-1 -p 80

app:
  build: .
  volumes:
    - ./ui:/usr/src/app/ui
    - ./webpack.config.js:/usr/src/app/webpack.config.js
  command: npm run watch
