webserver:
  build: .
  volumes:
    - .:/usr/src/app
  ports:
    - 3000:80
  command: http-server ./ui/public -c-1 -p 80

app:
  build: .
  volumes:
    - ./js:/usr/src/app/js
    - ./css:/usr/src/app/css
    - ./public:/usr/src/app/public
    - ./locales:/usr/src/app/locales
  command: npm run watch
